/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ScoreEntry { 'score' : bigint, 'playerName' : string }
export interface PvPRoom {
  'roomCode' : string,
  'player1' : string,
  'player2' : string,
  'gameType' : string,
  'gameState' : string,
  'currentTurn' : string,
  'status' : string,
  'winner' : string,
}
export interface _SERVICE {
  'clearLeaderboard' : ActorMethod<[], undefined>,
  'getTop10Scores' : ActorMethod<[], Array<ScoreEntry>>,
  'submitScore' : ActorMethod<[string, bigint], undefined>,
  'getTokenStatsJson' : ActorMethod<[], string>,
  'createPvPRoom' : ActorMethod<[string, string, string], string>,
  'joinPvPRoom' : ActorMethod<[string, string], boolean>,
  'getPvPRoom' : ActorMethod<[string], [] | [PvPRoom]>,
  'getWaitingRoom' : ActorMethod<[string, string], [] | [PvPRoom]>,
  'updatePvPState' : ActorMethod<[string, string, string, string], boolean>,
  'finishPvPGame' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
