/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ScoreEntry = IDL.Record({
  'score' : IDL.Nat,
  'playerName' : IDL.Text,
});

export const PvPRoom = IDL.Record({
  'roomCode' : IDL.Text,
  'player1' : IDL.Text,
  'player2' : IDL.Text,
  'gameType' : IDL.Text,
  'gameState' : IDL.Text,
  'currentTurn' : IDL.Text,
  'status' : IDL.Text,
  'winner' : IDL.Text,
});

export const idlService = IDL.Service({
  'clearLeaderboard' : IDL.Func([], [], []),
  'getTop10Scores' : IDL.Func([], [IDL.Vec(ScoreEntry)], ['query']),
  'submitScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'getTokenStatsJson' : IDL.Func([], [IDL.Text], []),
  'createPvPRoom' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'joinPvPRoom' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'getPvPRoom' : IDL.Func([IDL.Text], [IDL.Opt(PvPRoom)], ['query']),
  'getWaitingRoom' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(PvPRoom)], ['query']),
  'updatePvPState' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'finishPvPGame' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ScoreEntry = IDL.Record({ 'score' : IDL.Nat, 'playerName' : IDL.Text });
  const PvPRoom = IDL.Record({
    'roomCode' : IDL.Text,
    'player1' : IDL.Text,
    'player2' : IDL.Text,
    'gameType' : IDL.Text,
    'gameState' : IDL.Text,
    'currentTurn' : IDL.Text,
    'status' : IDL.Text,
    'winner' : IDL.Text,
  });
  
  return IDL.Service({
    'clearLeaderboard' : IDL.Func([], [], []),
    'getTop10Scores' : IDL.Func([], [IDL.Vec(ScoreEntry)], ['query']),
    'submitScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'getTokenStatsJson' : IDL.Func([], [IDL.Text], []),
    'createPvPRoom' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'joinPvPRoom' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'getPvPRoom' : IDL.Func([IDL.Text], [IDL.Opt(PvPRoom)], ['query']),
    'getWaitingRoom' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(PvPRoom)], ['query']),
    'updatePvPState' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
    'finishPvPGame' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };
