/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE, type PvPRoom as PvPRoomCandid } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ScoreEntry {
    score: bigint;
    playerName: string;
}
export interface PvPRoom {
    roomCode: string;
    player1: string;
    player2: string;
    gameType: string;
    gameState: string;
    currentTurn: string;
    status: string;
    winner: string;
}
export interface backendInterface {
    clearLeaderboard(): Promise<void>;
    getTop10Scores(): Promise<Array<ScoreEntry>>;
    submitScore(playerName: string, score: bigint): Promise<void>;
    getTokenStatsJson(): Promise<string>;
    createPvPRoom(player1: string, gameType: string, initialState: string): Promise<string>;
    joinPvPRoom(code: string, player2: string): Promise<boolean>;
    getPvPRoom(code: string): Promise<Option<PvPRoom>>;
    updatePvPState(code: string, playerAddr: string, newState: string, nextTurn: string): Promise<boolean>;
    finishPvPGame(code: string, winner: string): Promise<boolean>;
}

function candidOptToOption<T>(candidOpt: [] | [T]): Option<T> {
    if (candidOpt.length === 0) return { __kind__: "None" };
    return { __kind__: "Some", value: candidOpt[0] };
}

export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async clearLeaderboard(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error('unreachable');
            }
        } else {
            const result = await this.actor.clearLeaderboard();
            return result;
        }
    }
    async getTop10Scores(): Promise<Array<ScoreEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTop10Scores();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTop10Scores();
            return result;
        }
    }
    async submitScore(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitScore(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitScore(arg0, arg1);
            return result;
        }
    }
    async getTokenStatsJson(): Promise<string> {
        if (this.processError) {
            try {
                return await this.actor.getTokenStatsJson();
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.getTokenStatsJson();
        }
    }
    async createPvPRoom(player1: string, gameType: string, initialState: string): Promise<string> {
        if (this.processError) {
            try {
                return await this.actor.createPvPRoom(player1, gameType, initialState);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.createPvPRoom(player1, gameType, initialState);
        }
    }
    async joinPvPRoom(code: string, player2: string): Promise<boolean> {
        if (this.processError) {
            try {
                return await this.actor.joinPvPRoom(code, player2);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.joinPvPRoom(code, player2);
        }
    }
    async getPvPRoom(code: string): Promise<Option<PvPRoom>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPvPRoom(code);
                return candidOptToOption(result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPvPRoom(code);
            return candidOptToOption(result);
        }
    }
    async updatePvPState(code: string, playerAddr: string, newState: string, nextTurn: string): Promise<boolean> {
        if (this.processError) {
            try {
                return await this.actor.updatePvPState(code, playerAddr, newState, nextTurn);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.updatePvPState(code, playerAddr, newState, nextTurn);
        }
    }
    async finishPvPGame(code: string, winner: string): Promise<boolean> {
        if (this.processError) {
            try {
                return await this.actor.finishPvPGame(code, winner);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.finishPvPGame(code, winner);
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
